before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/warp.go
    binary: "warp_swagger"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le

archives:
  - format: binary
    wrap_in_directory: false
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'